// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: customer.proto

package com.pluralsight.protocolbuffers;

public final class CustomerProtoBuf {
  private CustomerProtoBuf() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface CustomerPBOrBuilder extends
      // @@protoc_insertion_point(interface_extends:CustomerPB)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string first_name = 1;</code>
     */
    java.lang.String getFirstName();
    /**
     * <code>optional string first_name = 1;</code>
     */
    com.google.protobuf.ByteString
        getFirstNameBytes();

    /**
     * <code>optional string last_name = 2;</code>
     */
    java.lang.String getLastName();
    /**
     * <code>optional string last_name = 2;</code>
     */
    com.google.protobuf.ByteString
        getLastNameBytes();

    /**
     * <code>optional .AddressPB address = 3;</code>
     */
    boolean hasAddress();
    /**
     * <code>optional .AddressPB address = 3;</code>
     */
    com.pluralsight.protocolbuffers.CustomerProtoBuf.AddressPB getAddress();
    /**
     * <code>optional .AddressPB address = 3;</code>
     */
    com.pluralsight.protocolbuffers.CustomerProtoBuf.AddressPBOrBuilder getAddressOrBuilder();
  }
  /**
   * Protobuf type {@code CustomerPB}
   */
  public  static final class CustomerPB extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:CustomerPB)
      CustomerPBOrBuilder {
    // Use CustomerPB.newBuilder() to construct.
    private CustomerPB(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private CustomerPB() {
      firstName_ = "";
      lastName_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private CustomerPB(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              firstName_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              lastName_ = s;
              break;
            }
            case 26: {
              com.pluralsight.protocolbuffers.CustomerProtoBuf.AddressPB.Builder subBuilder = null;
              if (address_ != null) {
                subBuilder = address_.toBuilder();
              }
              address_ = input.readMessage(com.pluralsight.protocolbuffers.CustomerProtoBuf.AddressPB.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(address_);
                address_ = subBuilder.buildPartial();
              }

              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.pluralsight.protocolbuffers.CustomerProtoBuf.internal_static_CustomerPB_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.pluralsight.protocolbuffers.CustomerProtoBuf.internal_static_CustomerPB_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.pluralsight.protocolbuffers.CustomerProtoBuf.CustomerPB.class, com.pluralsight.protocolbuffers.CustomerProtoBuf.CustomerPB.Builder.class);
    }

    public static final int FIRST_NAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object firstName_;
    /**
     * <code>optional string first_name = 1;</code>
     */
    public java.lang.String getFirstName() {
      java.lang.Object ref = firstName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        firstName_ = s;
        return s;
      }
    }
    /**
     * <code>optional string first_name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getFirstNameBytes() {
      java.lang.Object ref = firstName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        firstName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LAST_NAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object lastName_;
    /**
     * <code>optional string last_name = 2;</code>
     */
    public java.lang.String getLastName() {
      java.lang.Object ref = lastName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        lastName_ = s;
        return s;
      }
    }
    /**
     * <code>optional string last_name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getLastNameBytes() {
      java.lang.Object ref = lastName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        lastName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ADDRESS_FIELD_NUMBER = 3;
    private com.pluralsight.protocolbuffers.CustomerProtoBuf.AddressPB address_;
    /**
     * <code>optional .AddressPB address = 3;</code>
     */
    public boolean hasAddress() {
      return address_ != null;
    }
    /**
     * <code>optional .AddressPB address = 3;</code>
     */
    public com.pluralsight.protocolbuffers.CustomerProtoBuf.AddressPB getAddress() {
      return address_ == null ? com.pluralsight.protocolbuffers.CustomerProtoBuf.AddressPB.getDefaultInstance() : address_;
    }
    /**
     * <code>optional .AddressPB address = 3;</code>
     */
    public com.pluralsight.protocolbuffers.CustomerProtoBuf.AddressPBOrBuilder getAddressOrBuilder() {
      return getAddress();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getFirstNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, firstName_);
      }
      if (!getLastNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessage.writeString(output, 2, lastName_);
      }
      if (address_ != null) {
        output.writeMessage(3, getAddress());
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getFirstNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, firstName_);
      }
      if (!getLastNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(2, lastName_);
      }
      if (address_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getAddress());
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static com.pluralsight.protocolbuffers.CustomerProtoBuf.CustomerPB parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.pluralsight.protocolbuffers.CustomerProtoBuf.CustomerPB parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.pluralsight.protocolbuffers.CustomerProtoBuf.CustomerPB parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.pluralsight.protocolbuffers.CustomerProtoBuf.CustomerPB parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.pluralsight.protocolbuffers.CustomerProtoBuf.CustomerPB parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.pluralsight.protocolbuffers.CustomerProtoBuf.CustomerPB parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.pluralsight.protocolbuffers.CustomerProtoBuf.CustomerPB parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.pluralsight.protocolbuffers.CustomerProtoBuf.CustomerPB parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.pluralsight.protocolbuffers.CustomerProtoBuf.CustomerPB parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.pluralsight.protocolbuffers.CustomerProtoBuf.CustomerPB parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.pluralsight.protocolbuffers.CustomerProtoBuf.CustomerPB prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code CustomerPB}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:CustomerPB)
        com.pluralsight.protocolbuffers.CustomerProtoBuf.CustomerPBOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.pluralsight.protocolbuffers.CustomerProtoBuf.internal_static_CustomerPB_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.pluralsight.protocolbuffers.CustomerProtoBuf.internal_static_CustomerPB_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.pluralsight.protocolbuffers.CustomerProtoBuf.CustomerPB.class, com.pluralsight.protocolbuffers.CustomerProtoBuf.CustomerPB.Builder.class);
      }

      // Construct using com.pluralsight.protocolbuffers.CustomerProtoBuf.CustomerPB.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        firstName_ = "";

        lastName_ = "";

        if (addressBuilder_ == null) {
          address_ = null;
        } else {
          address_ = null;
          addressBuilder_ = null;
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.pluralsight.protocolbuffers.CustomerProtoBuf.internal_static_CustomerPB_descriptor;
      }

      public com.pluralsight.protocolbuffers.CustomerProtoBuf.CustomerPB getDefaultInstanceForType() {
        return com.pluralsight.protocolbuffers.CustomerProtoBuf.CustomerPB.getDefaultInstance();
      }

      public com.pluralsight.protocolbuffers.CustomerProtoBuf.CustomerPB build() {
        com.pluralsight.protocolbuffers.CustomerProtoBuf.CustomerPB result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.pluralsight.protocolbuffers.CustomerProtoBuf.CustomerPB buildPartial() {
        com.pluralsight.protocolbuffers.CustomerProtoBuf.CustomerPB result = new com.pluralsight.protocolbuffers.CustomerProtoBuf.CustomerPB(this);
        result.firstName_ = firstName_;
        result.lastName_ = lastName_;
        if (addressBuilder_ == null) {
          result.address_ = address_;
        } else {
          result.address_ = addressBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.pluralsight.protocolbuffers.CustomerProtoBuf.CustomerPB) {
          return mergeFrom((com.pluralsight.protocolbuffers.CustomerProtoBuf.CustomerPB)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.pluralsight.protocolbuffers.CustomerProtoBuf.CustomerPB other) {
        if (other == com.pluralsight.protocolbuffers.CustomerProtoBuf.CustomerPB.getDefaultInstance()) return this;
        if (!other.getFirstName().isEmpty()) {
          firstName_ = other.firstName_;
          onChanged();
        }
        if (!other.getLastName().isEmpty()) {
          lastName_ = other.lastName_;
          onChanged();
        }
        if (other.hasAddress()) {
          mergeAddress(other.getAddress());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.pluralsight.protocolbuffers.CustomerProtoBuf.CustomerPB parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.pluralsight.protocolbuffers.CustomerProtoBuf.CustomerPB) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object firstName_ = "";
      /**
       * <code>optional string first_name = 1;</code>
       */
      public java.lang.String getFirstName() {
        java.lang.Object ref = firstName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          firstName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string first_name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getFirstNameBytes() {
        java.lang.Object ref = firstName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          firstName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string first_name = 1;</code>
       */
      public Builder setFirstName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        firstName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string first_name = 1;</code>
       */
      public Builder clearFirstName() {
        
        firstName_ = getDefaultInstance().getFirstName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string first_name = 1;</code>
       */
      public Builder setFirstNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        firstName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object lastName_ = "";
      /**
       * <code>optional string last_name = 2;</code>
       */
      public java.lang.String getLastName() {
        java.lang.Object ref = lastName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          lastName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string last_name = 2;</code>
       */
      public com.google.protobuf.ByteString
          getLastNameBytes() {
        java.lang.Object ref = lastName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          lastName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string last_name = 2;</code>
       */
      public Builder setLastName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        lastName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string last_name = 2;</code>
       */
      public Builder clearLastName() {
        
        lastName_ = getDefaultInstance().getLastName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string last_name = 2;</code>
       */
      public Builder setLastNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        lastName_ = value;
        onChanged();
        return this;
      }

      private com.pluralsight.protocolbuffers.CustomerProtoBuf.AddressPB address_ = null;
      private com.google.protobuf.SingleFieldBuilder<
          com.pluralsight.protocolbuffers.CustomerProtoBuf.AddressPB, com.pluralsight.protocolbuffers.CustomerProtoBuf.AddressPB.Builder, com.pluralsight.protocolbuffers.CustomerProtoBuf.AddressPBOrBuilder> addressBuilder_;
      /**
       * <code>optional .AddressPB address = 3;</code>
       */
      public boolean hasAddress() {
        return addressBuilder_ != null || address_ != null;
      }
      /**
       * <code>optional .AddressPB address = 3;</code>
       */
      public com.pluralsight.protocolbuffers.CustomerProtoBuf.AddressPB getAddress() {
        if (addressBuilder_ == null) {
          return address_ == null ? com.pluralsight.protocolbuffers.CustomerProtoBuf.AddressPB.getDefaultInstance() : address_;
        } else {
          return addressBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .AddressPB address = 3;</code>
       */
      public Builder setAddress(com.pluralsight.protocolbuffers.CustomerProtoBuf.AddressPB value) {
        if (addressBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          address_ = value;
          onChanged();
        } else {
          addressBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>optional .AddressPB address = 3;</code>
       */
      public Builder setAddress(
          com.pluralsight.protocolbuffers.CustomerProtoBuf.AddressPB.Builder builderForValue) {
        if (addressBuilder_ == null) {
          address_ = builderForValue.build();
          onChanged();
        } else {
          addressBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>optional .AddressPB address = 3;</code>
       */
      public Builder mergeAddress(com.pluralsight.protocolbuffers.CustomerProtoBuf.AddressPB value) {
        if (addressBuilder_ == null) {
          if (address_ != null) {
            address_ =
              com.pluralsight.protocolbuffers.CustomerProtoBuf.AddressPB.newBuilder(address_).mergeFrom(value).buildPartial();
          } else {
            address_ = value;
          }
          onChanged();
        } else {
          addressBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>optional .AddressPB address = 3;</code>
       */
      public Builder clearAddress() {
        if (addressBuilder_ == null) {
          address_ = null;
          onChanged();
        } else {
          address_ = null;
          addressBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>optional .AddressPB address = 3;</code>
       */
      public com.pluralsight.protocolbuffers.CustomerProtoBuf.AddressPB.Builder getAddressBuilder() {
        
        onChanged();
        return getAddressFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .AddressPB address = 3;</code>
       */
      public com.pluralsight.protocolbuffers.CustomerProtoBuf.AddressPBOrBuilder getAddressOrBuilder() {
        if (addressBuilder_ != null) {
          return addressBuilder_.getMessageOrBuilder();
        } else {
          return address_ == null ?
              com.pluralsight.protocolbuffers.CustomerProtoBuf.AddressPB.getDefaultInstance() : address_;
        }
      }
      /**
       * <code>optional .AddressPB address = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.pluralsight.protocolbuffers.CustomerProtoBuf.AddressPB, com.pluralsight.protocolbuffers.CustomerProtoBuf.AddressPB.Builder, com.pluralsight.protocolbuffers.CustomerProtoBuf.AddressPBOrBuilder> 
          getAddressFieldBuilder() {
        if (addressBuilder_ == null) {
          addressBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.pluralsight.protocolbuffers.CustomerProtoBuf.AddressPB, com.pluralsight.protocolbuffers.CustomerProtoBuf.AddressPB.Builder, com.pluralsight.protocolbuffers.CustomerProtoBuf.AddressPBOrBuilder>(
                  getAddress(),
                  getParentForChildren(),
                  isClean());
          address_ = null;
        }
        return addressBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:CustomerPB)
    }

    // @@protoc_insertion_point(class_scope:CustomerPB)
    private static final com.pluralsight.protocolbuffers.CustomerProtoBuf.CustomerPB DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.pluralsight.protocolbuffers.CustomerProtoBuf.CustomerPB();
    }

    public static com.pluralsight.protocolbuffers.CustomerProtoBuf.CustomerPB getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CustomerPB>
        PARSER = new com.google.protobuf.AbstractParser<CustomerPB>() {
      public CustomerPB parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new CustomerPB(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CustomerPB> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CustomerPB> getParserForType() {
      return PARSER;
    }

    public com.pluralsight.protocolbuffers.CustomerProtoBuf.CustomerPB getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface AddressPBOrBuilder extends
      // @@protoc_insertion_point(interface_extends:AddressPB)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string address1 = 1;</code>
     */
    java.lang.String getAddress1();
    /**
     * <code>optional string address1 = 1;</code>
     */
    com.google.protobuf.ByteString
        getAddress1Bytes();

    /**
     * <code>optional string address2 = 2;</code>
     */
    java.lang.String getAddress2();
    /**
     * <code>optional string address2 = 2;</code>
     */
    com.google.protobuf.ByteString
        getAddress2Bytes();

    /**
     * <code>optional string city = 3;</code>
     */
    java.lang.String getCity();
    /**
     * <code>optional string city = 3;</code>
     */
    com.google.protobuf.ByteString
        getCityBytes();

    /**
     * <code>optional string state = 4;</code>
     */
    java.lang.String getState();
    /**
     * <code>optional string state = 4;</code>
     */
    com.google.protobuf.ByteString
        getStateBytes();

    /**
     * <code>optional string zip_code = 5;</code>
     */
    java.lang.String getZipCode();
    /**
     * <code>optional string zip_code = 5;</code>
     */
    com.google.protobuf.ByteString
        getZipCodeBytes();
  }
  /**
   * Protobuf type {@code AddressPB}
   */
  public  static final class AddressPB extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:AddressPB)
      AddressPBOrBuilder {
    // Use AddressPB.newBuilder() to construct.
    private AddressPB(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private AddressPB() {
      address1_ = "";
      address2_ = "";
      city_ = "";
      state_ = "";
      zipCode_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private AddressPB(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              address1_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              address2_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              city_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              state_ = s;
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              zipCode_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.pluralsight.protocolbuffers.CustomerProtoBuf.internal_static_AddressPB_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.pluralsight.protocolbuffers.CustomerProtoBuf.internal_static_AddressPB_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.pluralsight.protocolbuffers.CustomerProtoBuf.AddressPB.class, com.pluralsight.protocolbuffers.CustomerProtoBuf.AddressPB.Builder.class);
    }

    public static final int ADDRESS1_FIELD_NUMBER = 1;
    private volatile java.lang.Object address1_;
    /**
     * <code>optional string address1 = 1;</code>
     */
    public java.lang.String getAddress1() {
      java.lang.Object ref = address1_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        address1_ = s;
        return s;
      }
    }
    /**
     * <code>optional string address1 = 1;</code>
     */
    public com.google.protobuf.ByteString
        getAddress1Bytes() {
      java.lang.Object ref = address1_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        address1_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ADDRESS2_FIELD_NUMBER = 2;
    private volatile java.lang.Object address2_;
    /**
     * <code>optional string address2 = 2;</code>
     */
    public java.lang.String getAddress2() {
      java.lang.Object ref = address2_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        address2_ = s;
        return s;
      }
    }
    /**
     * <code>optional string address2 = 2;</code>
     */
    public com.google.protobuf.ByteString
        getAddress2Bytes() {
      java.lang.Object ref = address2_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        address2_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CITY_FIELD_NUMBER = 3;
    private volatile java.lang.Object city_;
    /**
     * <code>optional string city = 3;</code>
     */
    public java.lang.String getCity() {
      java.lang.Object ref = city_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        city_ = s;
        return s;
      }
    }
    /**
     * <code>optional string city = 3;</code>
     */
    public com.google.protobuf.ByteString
        getCityBytes() {
      java.lang.Object ref = city_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        city_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int STATE_FIELD_NUMBER = 4;
    private volatile java.lang.Object state_;
    /**
     * <code>optional string state = 4;</code>
     */
    public java.lang.String getState() {
      java.lang.Object ref = state_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        state_ = s;
        return s;
      }
    }
    /**
     * <code>optional string state = 4;</code>
     */
    public com.google.protobuf.ByteString
        getStateBytes() {
      java.lang.Object ref = state_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        state_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ZIP_CODE_FIELD_NUMBER = 5;
    private volatile java.lang.Object zipCode_;
    /**
     * <code>optional string zip_code = 5;</code>
     */
    public java.lang.String getZipCode() {
      java.lang.Object ref = zipCode_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        zipCode_ = s;
        return s;
      }
    }
    /**
     * <code>optional string zip_code = 5;</code>
     */
    public com.google.protobuf.ByteString
        getZipCodeBytes() {
      java.lang.Object ref = zipCode_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        zipCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getAddress1Bytes().isEmpty()) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, address1_);
      }
      if (!getAddress2Bytes().isEmpty()) {
        com.google.protobuf.GeneratedMessage.writeString(output, 2, address2_);
      }
      if (!getCityBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessage.writeString(output, 3, city_);
      }
      if (!getStateBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessage.writeString(output, 4, state_);
      }
      if (!getZipCodeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessage.writeString(output, 5, zipCode_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getAddress1Bytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, address1_);
      }
      if (!getAddress2Bytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(2, address2_);
      }
      if (!getCityBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(3, city_);
      }
      if (!getStateBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(4, state_);
      }
      if (!getZipCodeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(5, zipCode_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static com.pluralsight.protocolbuffers.CustomerProtoBuf.AddressPB parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.pluralsight.protocolbuffers.CustomerProtoBuf.AddressPB parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.pluralsight.protocolbuffers.CustomerProtoBuf.AddressPB parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.pluralsight.protocolbuffers.CustomerProtoBuf.AddressPB parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.pluralsight.protocolbuffers.CustomerProtoBuf.AddressPB parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.pluralsight.protocolbuffers.CustomerProtoBuf.AddressPB parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.pluralsight.protocolbuffers.CustomerProtoBuf.AddressPB parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.pluralsight.protocolbuffers.CustomerProtoBuf.AddressPB parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.pluralsight.protocolbuffers.CustomerProtoBuf.AddressPB parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.pluralsight.protocolbuffers.CustomerProtoBuf.AddressPB parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.pluralsight.protocolbuffers.CustomerProtoBuf.AddressPB prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code AddressPB}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:AddressPB)
        com.pluralsight.protocolbuffers.CustomerProtoBuf.AddressPBOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.pluralsight.protocolbuffers.CustomerProtoBuf.internal_static_AddressPB_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.pluralsight.protocolbuffers.CustomerProtoBuf.internal_static_AddressPB_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.pluralsight.protocolbuffers.CustomerProtoBuf.AddressPB.class, com.pluralsight.protocolbuffers.CustomerProtoBuf.AddressPB.Builder.class);
      }

      // Construct using com.pluralsight.protocolbuffers.CustomerProtoBuf.AddressPB.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        address1_ = "";

        address2_ = "";

        city_ = "";

        state_ = "";

        zipCode_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.pluralsight.protocolbuffers.CustomerProtoBuf.internal_static_AddressPB_descriptor;
      }

      public com.pluralsight.protocolbuffers.CustomerProtoBuf.AddressPB getDefaultInstanceForType() {
        return com.pluralsight.protocolbuffers.CustomerProtoBuf.AddressPB.getDefaultInstance();
      }

      public com.pluralsight.protocolbuffers.CustomerProtoBuf.AddressPB build() {
        com.pluralsight.protocolbuffers.CustomerProtoBuf.AddressPB result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.pluralsight.protocolbuffers.CustomerProtoBuf.AddressPB buildPartial() {
        com.pluralsight.protocolbuffers.CustomerProtoBuf.AddressPB result = new com.pluralsight.protocolbuffers.CustomerProtoBuf.AddressPB(this);
        result.address1_ = address1_;
        result.address2_ = address2_;
        result.city_ = city_;
        result.state_ = state_;
        result.zipCode_ = zipCode_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.pluralsight.protocolbuffers.CustomerProtoBuf.AddressPB) {
          return mergeFrom((com.pluralsight.protocolbuffers.CustomerProtoBuf.AddressPB)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.pluralsight.protocolbuffers.CustomerProtoBuf.AddressPB other) {
        if (other == com.pluralsight.protocolbuffers.CustomerProtoBuf.AddressPB.getDefaultInstance()) return this;
        if (!other.getAddress1().isEmpty()) {
          address1_ = other.address1_;
          onChanged();
        }
        if (!other.getAddress2().isEmpty()) {
          address2_ = other.address2_;
          onChanged();
        }
        if (!other.getCity().isEmpty()) {
          city_ = other.city_;
          onChanged();
        }
        if (!other.getState().isEmpty()) {
          state_ = other.state_;
          onChanged();
        }
        if (!other.getZipCode().isEmpty()) {
          zipCode_ = other.zipCode_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.pluralsight.protocolbuffers.CustomerProtoBuf.AddressPB parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.pluralsight.protocolbuffers.CustomerProtoBuf.AddressPB) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object address1_ = "";
      /**
       * <code>optional string address1 = 1;</code>
       */
      public java.lang.String getAddress1() {
        java.lang.Object ref = address1_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          address1_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string address1 = 1;</code>
       */
      public com.google.protobuf.ByteString
          getAddress1Bytes() {
        java.lang.Object ref = address1_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          address1_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string address1 = 1;</code>
       */
      public Builder setAddress1(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        address1_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string address1 = 1;</code>
       */
      public Builder clearAddress1() {
        
        address1_ = getDefaultInstance().getAddress1();
        onChanged();
        return this;
      }
      /**
       * <code>optional string address1 = 1;</code>
       */
      public Builder setAddress1Bytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        address1_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object address2_ = "";
      /**
       * <code>optional string address2 = 2;</code>
       */
      public java.lang.String getAddress2() {
        java.lang.Object ref = address2_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          address2_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string address2 = 2;</code>
       */
      public com.google.protobuf.ByteString
          getAddress2Bytes() {
        java.lang.Object ref = address2_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          address2_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string address2 = 2;</code>
       */
      public Builder setAddress2(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        address2_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string address2 = 2;</code>
       */
      public Builder clearAddress2() {
        
        address2_ = getDefaultInstance().getAddress2();
        onChanged();
        return this;
      }
      /**
       * <code>optional string address2 = 2;</code>
       */
      public Builder setAddress2Bytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        address2_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object city_ = "";
      /**
       * <code>optional string city = 3;</code>
       */
      public java.lang.String getCity() {
        java.lang.Object ref = city_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          city_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string city = 3;</code>
       */
      public com.google.protobuf.ByteString
          getCityBytes() {
        java.lang.Object ref = city_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          city_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string city = 3;</code>
       */
      public Builder setCity(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        city_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string city = 3;</code>
       */
      public Builder clearCity() {
        
        city_ = getDefaultInstance().getCity();
        onChanged();
        return this;
      }
      /**
       * <code>optional string city = 3;</code>
       */
      public Builder setCityBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        city_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object state_ = "";
      /**
       * <code>optional string state = 4;</code>
       */
      public java.lang.String getState() {
        java.lang.Object ref = state_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          state_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string state = 4;</code>
       */
      public com.google.protobuf.ByteString
          getStateBytes() {
        java.lang.Object ref = state_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          state_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string state = 4;</code>
       */
      public Builder setState(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        state_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string state = 4;</code>
       */
      public Builder clearState() {
        
        state_ = getDefaultInstance().getState();
        onChanged();
        return this;
      }
      /**
       * <code>optional string state = 4;</code>
       */
      public Builder setStateBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        state_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object zipCode_ = "";
      /**
       * <code>optional string zip_code = 5;</code>
       */
      public java.lang.String getZipCode() {
        java.lang.Object ref = zipCode_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          zipCode_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string zip_code = 5;</code>
       */
      public com.google.protobuf.ByteString
          getZipCodeBytes() {
        java.lang.Object ref = zipCode_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          zipCode_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string zip_code = 5;</code>
       */
      public Builder setZipCode(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        zipCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string zip_code = 5;</code>
       */
      public Builder clearZipCode() {
        
        zipCode_ = getDefaultInstance().getZipCode();
        onChanged();
        return this;
      }
      /**
       * <code>optional string zip_code = 5;</code>
       */
      public Builder setZipCodeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        zipCode_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:AddressPB)
    }

    // @@protoc_insertion_point(class_scope:AddressPB)
    private static final com.pluralsight.protocolbuffers.CustomerProtoBuf.AddressPB DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.pluralsight.protocolbuffers.CustomerProtoBuf.AddressPB();
    }

    public static com.pluralsight.protocolbuffers.CustomerProtoBuf.AddressPB getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<AddressPB>
        PARSER = new com.google.protobuf.AbstractParser<AddressPB>() {
      public AddressPB parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new AddressPB(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<AddressPB> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<AddressPB> getParserForType() {
      return PARSER;
    }

    public com.pluralsight.protocolbuffers.CustomerProtoBuf.AddressPB getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CustomerPB_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_CustomerPB_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AddressPB_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_AddressPB_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016customer.proto\"P\n\nCustomerPB\022\022\n\nfirst_" +
      "name\030\001 \001(\t\022\021\n\tlast_name\030\002 \001(\t\022\033\n\007address" +
      "\030\003 \001(\0132\n.AddressPB\"^\n\tAddressPB\022\020\n\010addre" +
      "ss1\030\001 \001(\t\022\020\n\010address2\030\002 \001(\t\022\014\n\004city\030\003 \001(" +
      "\t\022\r\n\005state\030\004 \001(\t\022\020\n\010zip_code\030\005 \001(\tB3\n\037co" +
      "m.pluralsight.protocolbuffersB\020CustomerP" +
      "rotoBufb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_CustomerPB_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_CustomerPB_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_CustomerPB_descriptor,
        new java.lang.String[] { "FirstName", "LastName", "Address", });
    internal_static_AddressPB_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_AddressPB_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_AddressPB_descriptor,
        new java.lang.String[] { "Address1", "Address2", "City", "State", "ZipCode", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
