# Generated by Django 2.2.5 on 2019-10-25 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.TextField(blank=True, null=True, verbose_name='Topic')),
                ('CreatedDate', models.DateTimeField(auto_now_add=True, verbose_name='Blog_CreatedDate')),
                ('blog_created_by', models.CharField(max_length=100)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authors.User')),
            ],
        ),
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_no', models.IntegerField(default=0)),
                ('detail_element', models.CharField(choices=[('h1', 'Header'), ('h2', 'Header 2'), ('h3', 'Header 3'), ('h4', 'Header 4'), ('h5', 'Header 5'), ('h6', 'Header 6'), ('p', 'Paragraph'), ('ul', 'UnorderedLine'), ('ol', 'OrderedLine'), ('img', 'Images'), ('a', 'Anchor'), ('br', 'LineBreak')], max_length=100)),
                ('element_text', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='details_created_date')),
                ('created_by', models.CharField(max_length=100)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogs.Header')),
                ('detail_created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authors.User')),
            ],
        ),
    ]
