# Generated by Django 2.2.5 on 2019-10-26 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_auto_20191026_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='image_title',
            field=models.CharField(default='Image', max_length=100, null=True),
        ),
    ]
