# Generated by Django 2.2.5 on 2019-10-25 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_type', models.CharField(max_length=50)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=500)),
                ('country', models.CharField(choices=[('IN', 'INDIA'), ('USA', 'United States of America'), ('CN', 'China'), ('RU', 'Russia')], max_length=100)),
                ('create_date', models.DateTimeField(verbose_name='bloger_Creation_Date')),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('credit_limit', models.IntegerField(default=100000)),
                ('created_by', models.CharField(max_length=100)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authors.BlogType')),
            ],
        ),
    ]
