# Generated by Django 2.2.2 on 2019-06-18 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='move',
            name='status',
            field=models.CharField(default='F', max_length=1),
        ),
    ]
