// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: address.proto

public final class AddressOuterClass {
  private AddressOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface AddressOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Address)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string address = 1 [deprecated = true];</code>
     */
    @java.lang.Deprecated java.lang.String getAddress();
    /**
     * <code>optional string address = 1 [deprecated = true];</code>
     */
    @java.lang.Deprecated com.google.protobuf.ByteString
        getAddressBytes();

    /**
     * <code>optional string address1 = 6;</code>
     */
    java.lang.String getAddress1();
    /**
     * <code>optional string address1 = 6;</code>
     */
    com.google.protobuf.ByteString
        getAddress1Bytes();

    /**
     * <code>optional string address2 = 5;</code>
     */
    java.lang.String getAddress2();
    /**
     * <code>optional string address2 = 5;</code>
     */
    com.google.protobuf.ByteString
        getAddress2Bytes();

    /**
     * <code>optional string city = 2;</code>
     */
    java.lang.String getCity();
    /**
     * <code>optional string city = 2;</code>
     */
    com.google.protobuf.ByteString
        getCityBytes();

    /**
     * <code>optional string state = 3;</code>
     */
    java.lang.String getState();
    /**
     * <code>optional string state = 3;</code>
     */
    com.google.protobuf.ByteString
        getStateBytes();

    /**
     * <code>optional string zip_code = 4;</code>
     */
    java.lang.String getZipCode();
    /**
     * <code>optional string zip_code = 4;</code>
     */
    com.google.protobuf.ByteString
        getZipCodeBytes();
  }
  /**
   * Protobuf type {@code Address}
   */
  public  static final class Address extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:Address)
      AddressOrBuilder {
    // Use Address.newBuilder() to construct.
    private Address(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private Address() {
      address_ = "";
      address1_ = "";
      address2_ = "";
      city_ = "";
      state_ = "";
      zipCode_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Address(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              address_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              city_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              state_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              zipCode_ = s;
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              address2_ = s;
              break;
            }
            case 50: {
              java.lang.String s = input.readStringRequireUtf8();

              address1_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return AddressOuterClass.internal_static_Address_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return AddressOuterClass.internal_static_Address_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              AddressOuterClass.Address.class, AddressOuterClass.Address.Builder.class);
    }

    public static final int ADDRESS_FIELD_NUMBER = 1;
    private volatile java.lang.Object address_;
    /**
     * <code>optional string address = 1 [deprecated = true];</code>
     */
    @java.lang.Deprecated public java.lang.String getAddress() {
      java.lang.Object ref = address_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        address_ = s;
        return s;
      }
    }
    /**
     * <code>optional string address = 1 [deprecated = true];</code>
     */
    @java.lang.Deprecated public com.google.protobuf.ByteString
        getAddressBytes() {
      java.lang.Object ref = address_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        address_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ADDRESS1_FIELD_NUMBER = 6;
    private volatile java.lang.Object address1_;
    /**
     * <code>optional string address1 = 6;</code>
     */
    public java.lang.String getAddress1() {
      java.lang.Object ref = address1_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        address1_ = s;
        return s;
      }
    }
    /**
     * <code>optional string address1 = 6;</code>
     */
    public com.google.protobuf.ByteString
        getAddress1Bytes() {
      java.lang.Object ref = address1_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        address1_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ADDRESS2_FIELD_NUMBER = 5;
    private volatile java.lang.Object address2_;
    /**
     * <code>optional string address2 = 5;</code>
     */
    public java.lang.String getAddress2() {
      java.lang.Object ref = address2_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        address2_ = s;
        return s;
      }
    }
    /**
     * <code>optional string address2 = 5;</code>
     */
    public com.google.protobuf.ByteString
        getAddress2Bytes() {
      java.lang.Object ref = address2_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        address2_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CITY_FIELD_NUMBER = 2;
    private volatile java.lang.Object city_;
    /**
     * <code>optional string city = 2;</code>
     */
    public java.lang.String getCity() {
      java.lang.Object ref = city_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        city_ = s;
        return s;
      }
    }
    /**
     * <code>optional string city = 2;</code>
     */
    public com.google.protobuf.ByteString
        getCityBytes() {
      java.lang.Object ref = city_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        city_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int STATE_FIELD_NUMBER = 3;
    private volatile java.lang.Object state_;
    /**
     * <code>optional string state = 3;</code>
     */
    public java.lang.String getState() {
      java.lang.Object ref = state_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        state_ = s;
        return s;
      }
    }
    /**
     * <code>optional string state = 3;</code>
     */
    public com.google.protobuf.ByteString
        getStateBytes() {
      java.lang.Object ref = state_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        state_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ZIP_CODE_FIELD_NUMBER = 4;
    private volatile java.lang.Object zipCode_;
    /**
     * <code>optional string zip_code = 4;</code>
     */
    public java.lang.String getZipCode() {
      java.lang.Object ref = zipCode_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        zipCode_ = s;
        return s;
      }
    }
    /**
     * <code>optional string zip_code = 4;</code>
     */
    public com.google.protobuf.ByteString
        getZipCodeBytes() {
      java.lang.Object ref = zipCode_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        zipCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getAddressBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, address_);
      }
      if (!getCityBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessage.writeString(output, 2, city_);
      }
      if (!getStateBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessage.writeString(output, 3, state_);
      }
      if (!getZipCodeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessage.writeString(output, 4, zipCode_);
      }
      if (!getAddress2Bytes().isEmpty()) {
        com.google.protobuf.GeneratedMessage.writeString(output, 5, address2_);
      }
      if (!getAddress1Bytes().isEmpty()) {
        com.google.protobuf.GeneratedMessage.writeString(output, 6, address1_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getAddressBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, address_);
      }
      if (!getCityBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(2, city_);
      }
      if (!getStateBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(3, state_);
      }
      if (!getZipCodeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(4, zipCode_);
      }
      if (!getAddress2Bytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(5, address2_);
      }
      if (!getAddress1Bytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(6, address1_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static AddressOuterClass.Address parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static AddressOuterClass.Address parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static AddressOuterClass.Address parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static AddressOuterClass.Address parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static AddressOuterClass.Address parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static AddressOuterClass.Address parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static AddressOuterClass.Address parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static AddressOuterClass.Address parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static AddressOuterClass.Address parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static AddressOuterClass.Address parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(AddressOuterClass.Address prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Address}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Address)
        AddressOuterClass.AddressOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return AddressOuterClass.internal_static_Address_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return AddressOuterClass.internal_static_Address_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                AddressOuterClass.Address.class, AddressOuterClass.Address.Builder.class);
      }

      // Construct using AddressOuterClass.Address.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        address_ = "";

        address1_ = "";

        address2_ = "";

        city_ = "";

        state_ = "";

        zipCode_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return AddressOuterClass.internal_static_Address_descriptor;
      }

      public AddressOuterClass.Address getDefaultInstanceForType() {
        return AddressOuterClass.Address.getDefaultInstance();
      }

      public AddressOuterClass.Address build() {
        AddressOuterClass.Address result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public AddressOuterClass.Address buildPartial() {
        AddressOuterClass.Address result = new AddressOuterClass.Address(this);
        result.address_ = address_;
        result.address1_ = address1_;
        result.address2_ = address2_;
        result.city_ = city_;
        result.state_ = state_;
        result.zipCode_ = zipCode_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof AddressOuterClass.Address) {
          return mergeFrom((AddressOuterClass.Address)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(AddressOuterClass.Address other) {
        if (other == AddressOuterClass.Address.getDefaultInstance()) return this;
        if (!other.getAddress().isEmpty()) {
          address_ = other.address_;
          onChanged();
        }
        if (!other.getAddress1().isEmpty()) {
          address1_ = other.address1_;
          onChanged();
        }
        if (!other.getAddress2().isEmpty()) {
          address2_ = other.address2_;
          onChanged();
        }
        if (!other.getCity().isEmpty()) {
          city_ = other.city_;
          onChanged();
        }
        if (!other.getState().isEmpty()) {
          state_ = other.state_;
          onChanged();
        }
        if (!other.getZipCode().isEmpty()) {
          zipCode_ = other.zipCode_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        AddressOuterClass.Address parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (AddressOuterClass.Address) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object address_ = "";
      /**
       * <code>optional string address = 1 [deprecated = true];</code>
       */
      @java.lang.Deprecated public java.lang.String getAddress() {
        java.lang.Object ref = address_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          address_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string address = 1 [deprecated = true];</code>
       */
      @java.lang.Deprecated public com.google.protobuf.ByteString
          getAddressBytes() {
        java.lang.Object ref = address_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          address_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string address = 1 [deprecated = true];</code>
       */
      @java.lang.Deprecated public Builder setAddress(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        address_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string address = 1 [deprecated = true];</code>
       */
      @java.lang.Deprecated public Builder clearAddress() {
        
        address_ = getDefaultInstance().getAddress();
        onChanged();
        return this;
      }
      /**
       * <code>optional string address = 1 [deprecated = true];</code>
       */
      @java.lang.Deprecated public Builder setAddressBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        address_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object address1_ = "";
      /**
       * <code>optional string address1 = 6;</code>
       */
      public java.lang.String getAddress1() {
        java.lang.Object ref = address1_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          address1_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string address1 = 6;</code>
       */
      public com.google.protobuf.ByteString
          getAddress1Bytes() {
        java.lang.Object ref = address1_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          address1_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string address1 = 6;</code>
       */
      public Builder setAddress1(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        address1_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string address1 = 6;</code>
       */
      public Builder clearAddress1() {
        
        address1_ = getDefaultInstance().getAddress1();
        onChanged();
        return this;
      }
      /**
       * <code>optional string address1 = 6;</code>
       */
      public Builder setAddress1Bytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        address1_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object address2_ = "";
      /**
       * <code>optional string address2 = 5;</code>
       */
      public java.lang.String getAddress2() {
        java.lang.Object ref = address2_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          address2_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string address2 = 5;</code>
       */
      public com.google.protobuf.ByteString
          getAddress2Bytes() {
        java.lang.Object ref = address2_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          address2_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string address2 = 5;</code>
       */
      public Builder setAddress2(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        address2_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string address2 = 5;</code>
       */
      public Builder clearAddress2() {
        
        address2_ = getDefaultInstance().getAddress2();
        onChanged();
        return this;
      }
      /**
       * <code>optional string address2 = 5;</code>
       */
      public Builder setAddress2Bytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        address2_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object city_ = "";
      /**
       * <code>optional string city = 2;</code>
       */
      public java.lang.String getCity() {
        java.lang.Object ref = city_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          city_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string city = 2;</code>
       */
      public com.google.protobuf.ByteString
          getCityBytes() {
        java.lang.Object ref = city_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          city_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string city = 2;</code>
       */
      public Builder setCity(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        city_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string city = 2;</code>
       */
      public Builder clearCity() {
        
        city_ = getDefaultInstance().getCity();
        onChanged();
        return this;
      }
      /**
       * <code>optional string city = 2;</code>
       */
      public Builder setCityBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        city_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object state_ = "";
      /**
       * <code>optional string state = 3;</code>
       */
      public java.lang.String getState() {
        java.lang.Object ref = state_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          state_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string state = 3;</code>
       */
      public com.google.protobuf.ByteString
          getStateBytes() {
        java.lang.Object ref = state_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          state_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string state = 3;</code>
       */
      public Builder setState(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        state_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string state = 3;</code>
       */
      public Builder clearState() {
        
        state_ = getDefaultInstance().getState();
        onChanged();
        return this;
      }
      /**
       * <code>optional string state = 3;</code>
       */
      public Builder setStateBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        state_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object zipCode_ = "";
      /**
       * <code>optional string zip_code = 4;</code>
       */
      public java.lang.String getZipCode() {
        java.lang.Object ref = zipCode_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          zipCode_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string zip_code = 4;</code>
       */
      public com.google.protobuf.ByteString
          getZipCodeBytes() {
        java.lang.Object ref = zipCode_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          zipCode_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string zip_code = 4;</code>
       */
      public Builder setZipCode(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        zipCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string zip_code = 4;</code>
       */
      public Builder clearZipCode() {
        
        zipCode_ = getDefaultInstance().getZipCode();
        onChanged();
        return this;
      }
      /**
       * <code>optional string zip_code = 4;</code>
       */
      public Builder setZipCodeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        zipCode_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:Address)
    }

    // @@protoc_insertion_point(class_scope:Address)
    private static final AddressOuterClass.Address DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new AddressOuterClass.Address();
    }

    public static AddressOuterClass.Address getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Address>
        PARSER = new com.google.protobuf.AbstractParser<Address>() {
      public Address parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Address(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Address> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Address> getParserForType() {
      return PARSER;
    }

    public AddressOuterClass.Address getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Address_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Address_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\raddress.proto\"q\n\007Address\022\023\n\007address\030\001 " +
      "\001(\tB\002\030\001\022\020\n\010address1\030\006 \001(\t\022\020\n\010address2\030\005 " +
      "\001(\t\022\014\n\004city\030\002 \001(\t\022\r\n\005state\030\003 \001(\t\022\020\n\010zip_" +
      "code\030\004 \001(\tb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Address_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Address_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Address_descriptor,
        new java.lang.String[] { "Address", "Address1", "Address2", "City", "State", "ZipCode", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
